language: node_js
node_js:
- '5'
env:
- NODE_ENV=TEST CXX=g++-4.8
install:
- travis_retry npm install -g node-gyp
- travis_retry npm install
- sleep 15
script:
- travis_retry npm run lint
- travis_retry npm test
